-- AlterTable
ALTER TABLE "THRESHOLDS" ADD COLUMN     "cooldown_sec" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "max_pump_sec" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "temp_high" DOUBLE PRECISION NOT NULL DEFAULT 35;
