[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    ; Bỏ comment các thư viện cốt lõi này để code hoạt động được
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    
    ; Bổ sung thư viện WiFiManager siêu nhẹ (để cài WiFi qua điện thoại lần đầu)
    tzapu/WiFiManager @ ^2.0.16-rc.2

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    ; Đã xóa dòng -DELEGANTOTA_USE_ASYNC_WEBSERVER=1 vì không dùng Web nữa

board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.filesystem = littlefs