-- DropForeignKey
ALTER TABLE "ACTIVITY_LOGS" DROP CONSTRAINT "ACTIVITY_LOGS_Device_ID_fkey";

-- DropForeignKey
ALTER TABLE "ACTUATORS" DROP CONSTRAINT "ACTUATORS_Device_ID_fkey";

-- DropForeignKey
ALTER TABLE "ACTUATOR_LOGS" DROP CONSTRAINT "ACTUATOR_LOGS_Actuator_ID_fkey";

-- DropForeignKey
ALTER TABLE "DEVICES" DROP CONSTRAINT "DEVICES_User_ID_fkey";

-- DropForeignKey
ALTER TABLE "NOTIFICATION_CONFIGS" DROP CONSTRAINT "NOTIFICATION_CONFIGS_User_ID_fkey";

-- DropForeignKey
ALTER TABLE "PUMP_SAFETY_LOGS" DROP CONSTRAINT "PUMP_SAFETY_LOGS_Device_ID_fkey";

-- DropForeignKey
ALTER TABLE "SCHEDULES" DROP CONSTRAINT "SCHEDULES_Actuator_ID_fkey";

-- DropForeignKey
ALTER TABLE "SENSORS" DROP CONSTRAINT "SENSORS_Device_ID_fkey";

-- DropForeignKey
ALTER TABLE "SENSOR_READINGS" DROP CONSTRAINT "SENSOR_READINGS_Sensor_ID_fkey";

-- DropForeignKey
ALTER TABLE "SMART_LOGIC_CONFIGS" DROP CONSTRAINT "SMART_LOGIC_CONFIGS_Device_ID_fkey";

-- DropForeignKey
ALTER TABLE "THRESHOLDS" DROP CONSTRAINT "THRESHOLDS_Actuator_ID_fkey";

-- DropForeignKey
ALTER TABLE "THRESHOLDS" DROP CONSTRAINT "THRESHOLDS_Sensor_ID_fkey";

-- CreateIndex
CREATE INDEX "ACTIVITY_LOGS_Device_ID_occurred_at_idx" ON "ACTIVITY_LOGS"("Device_ID", "occurred_at");

-- AddForeignKey
ALTER TABLE "DEVICES" ADD CONSTRAINT "DEVICES_User_ID_fkey" FOREIGN KEY ("User_ID") REFERENCES "USERS"("User_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SENSORS" ADD CONSTRAINT "SENSORS_Device_ID_fkey" FOREIGN KEY ("Device_ID") REFERENCES "DEVICES"("Device_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTUATORS" ADD CONSTRAINT "ACTUATORS_Device_ID_fkey" FOREIGN KEY ("Device_ID") REFERENCES "DEVICES"("Device_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SENSOR_READINGS" ADD CONSTRAINT "SENSOR_READINGS_Sensor_ID_fkey" FOREIGN KEY ("Sensor_ID") REFERENCES "SENSORS"("Sensor_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTUATOR_LOGS" ADD CONSTRAINT "ACTUATOR_LOGS_Actuator_ID_fkey" FOREIGN KEY ("Actuator_ID") REFERENCES "ACTUATORS"("Actuator_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "THRESHOLDS" ADD CONSTRAINT "THRESHOLDS_Sensor_ID_fkey" FOREIGN KEY ("Sensor_ID") REFERENCES "SENSORS"("Sensor_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "THRESHOLDS" ADD CONSTRAINT "THRESHOLDS_Actuator_ID_fkey" FOREIGN KEY ("Actuator_ID") REFERENCES "ACTUATORS"("Actuator_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULES" ADD CONSTRAINT "SCHEDULES_Actuator_ID_fkey" FOREIGN KEY ("Actuator_ID") REFERENCES "ACTUATORS"("Actuator_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SMART_LOGIC_CONFIGS" ADD CONSTRAINT "SMART_LOGIC_CONFIGS_Device_ID_fkey" FOREIGN KEY ("Device_ID") REFERENCES "DEVICES"("Device_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION_CONFIGS" ADD CONSTRAINT "NOTIFICATION_CONFIGS_User_ID_fkey" FOREIGN KEY ("User_ID") REFERENCES "USERS"("User_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTIVITY_LOGS" ADD CONSTRAINT "ACTIVITY_LOGS_Device_ID_fkey" FOREIGN KEY ("Device_ID") REFERENCES "DEVICES"("Device_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUMP_SAFETY_LOGS" ADD CONSTRAINT "PUMP_SAFETY_LOGS_Device_ID_fkey" FOREIGN KEY ("Device_ID") REFERENCES "DEVICES"("Device_ID") ON DELETE CASCADE ON UPDATE CASCADE;
